# Site settings
title: IEEE VIS
email: web@ieeevis.org
description: > # this means to ignore newlines until "baseurl:"
  Website for IEEE VIS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ieeevis.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ['docs', 'data', 'extra', 'README.md', 'Makefile', 'scripts', 'files', '.DS_Store']

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      contact: "web@ieeevis.org"
